spring:
  application:
    name: config-server

management:
  endpoints:
    web:
      exposure:
        # 暴露触发消息总线的地址 actuator受制于请求方依赖项spring-boot-starter-actuator，是固定的
        include: actuator/config-refresh
