server:
  port: ${port:4080}
spring:
  application:
    name: gateway-service

  rabbitmq:
    host: localhost
    port: 5672
    username: root_msf
    password: 123456

  cloud:
    gateway:
      routes:
        # 路由id
        - id: welcome-service-route
          # 代理服务地址 - 断言命中后要转发到的真正的服务地址
          # uri: http://127.0.0.1:8081
          uri: lb://welcome-service
          # 断言 - 匹配映射路径
          predicates:
            # - Path=/users/**
            - Path=/welcome/**
          # 局部过滤器，仅针对匹配的本路由升效
          filters:
            # 添加前缀
            - PrefixPath=/users
            # 自定义局部过滤器
            - MyParam=name

        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/user/**
          # 局部过滤器，仅针对匹配的本路由升效
          filters:
            - PrefixPath=/users
            - MyParam=name
      # 默认过滤器，对所有路由都升效
      default-filter:
        # - 请求头属性名，请求头属性值，同一个过滤器，可以重复添加
        - AddRequestHeader=X-Request-Foo, Bar

      # 跨域设置
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - HEAD
              - PATCH
            allowedHeaders:
              - "*"
            exposedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600
