spring:
  cloud:
    gateway:
      routes:
        # 路由id
        - id: welcome-service-route
          # 代理服务地址 - 断言命中后要转发到的真正的服务地址
          uri: lb://welcome-service
          # 断言 - 匹配映射路径
          predicates:
            - Path=/welcome/**
          # 局部过滤器，仅针对匹配的本路由升效
          filters:
            # 添加前缀
            # - PrefixPath=/users
            # 删除前缀 welcome
            - StripPrefix=1

            # 自定义局部过滤器
            - MyParam=name

        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/api/v1/user/**
          # 局部过滤器，仅针对匹配的本路由升效
          filters:
            # 删除前缀 user
            - StripPrefix=3
            - MyParam=name

        - id: file-service-route
          uri: lb://file-service
          predicates:
            - Path=/api/v1/file/**
          # 局部过滤器，仅针对匹配的本路由升效
          filters:
            # 删除前缀 user
            - StripPrefix=3
            - MyParam=name

        - id: monitor-service-route
          uri: lb://monitor-service
          predicates:
            - Path=/api/v1/monitor/**
          # 局部过滤器，仅针对匹配的本路由升效
          filters:
            # 删除前缀 user
            - StripPrefix=3
