spring:
  application:
    name: gateway-service

  rabbitmq:
    host: localhost
    port: 5672
    username: root_msf
    password: 123456

  cloud:
    gateway:
      routes:
        # 路由id
        - id: welcome-service-route
          # 代理服务地址 - 断言命中后要转发到的真正的服务地址
          uri: lb://welcome-service
          # 断言 - 匹配映射路径
          predicates:
            - Path=/welcome/**
          # 局部过滤器，仅针对匹配的本路由升效
          filters:
            # 添加前缀
            # - PrefixPath=/users
            # 删除前缀 welcome
            - StripPrefix=1

            # 自定义局部过滤器
            - MyParam=name

        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/api/v1/user/**
          # 局部过滤器，仅针对匹配的本路由升效
          filters:
            # 删除前缀 user
            - StripPrefix=3
            - MyParam=name

        - id: file-service-route
          uri: lb://file-service
          predicates:
            - Path=/api/v1/upload/**
            - Path=/api/v1/download/**
          # 局部过滤器，仅针对匹配的本路由升效
          filters:
            # 删除前缀 user
            - StripPrefix=2
            - MyParam=name

        - id: monitor-service-route
          uri: lb://monitor-service
          predicates:
            - Path=/api/v1/monitor/**
          # 局部过滤器，仅针对匹配的本路由升效
          filters:
            # 删除前缀 user
            - StripPrefix=3

      # 默认过滤器，对所有路由都升效
      default-filter:
        # - 请求头属性名，请求头属性值，同一个过滤器，可以重复添加
        - AddRequestHeader=X-Request-Foo, Bar

      # 跨域设置
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOriginPatterns: "*"

            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - HEAD
              - PATCH
            allowedHeaders:
              - "*"
            exposedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600
            add-to-simple-url-handler-mapping: true
