server:
  port: ${port:8081}

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/macro-cloud
    username: root
    password: 123456
  # 配置本模块注册到服务中心的名称
  application:
    name: user-service

mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-alias-package: org.jeffchi.user.dto

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
      # defaultZone: http://localhost:10086/eureka,http://localhost:10087/eureka

    instance:
      ip-address: 127.0.0.1 # ip
      prefer-ip-address: true # 更倾向使用ip，而非 host名

      # 服务失效时间，默认90秒
      lease-expiration-duration-in-seconds: 90
      # 续约间隔，默认30秒
      lease-renewal-interval-in-seconds: 30
